
before_script:
  - python3 -m venv myenv
  - source myenv/bin/activate
  - pip3 install -r requirements.txt

after_script:
  - deactivate

stages:
  - unit_test
  - functional_test

unit_test_job:
  stage: unit_test
  script:
    - python3 -m unittest discover
  only:
    - master

smoke_test_job:
  stage: functional_test
  script:
    - ./FixToJson.py -h
    - ./GenerateTagMappings.py -h
    - ./ViewFix.py -h
  only:
    - master

functional_test_job:
  stage: functional_test
  script:
    - ./FixToJson.py data/secdef-test.dat
    - ./ViewFix.py data/secdef-test.dat
  only:
    - master
