
from .types import FIXTag

TAGS = [
	FIXTag(   1, 'Account', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   2, 'AdvId', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   3, 'AdvRefID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   4, 'AdvSide', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   5, 'AdvTransType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   6, 'AvgPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   7, 'BeginSeqNo', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   8, 'BeginString', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(   9, 'BodyLength', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  10, 'CheckSum', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  11, 'ClOrdID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  12, 'Commission', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  13, 'CommType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  14, 'CumQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  15, 'Currency', repeatingHeaderNumber=None, vendor='None', description='Identifies currency used for price.'),
	FIXTag(  16, 'EndSeqNo', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  17, 'ExecID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  18, 'ExecInst', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  19, 'ExecRefID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  20, 'ExecTransType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  21, 'HandlInst', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  22, 'IDSource', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  23, 'IOIid', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  24, 'IOIOthSvc', repeatingHeaderNumber=None, vendor='None', description='No longer used'),
	FIXTag(  25, 'IOIQltyInd', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  26, 'IOIRefID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  27, 'IOIShares', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  28, 'IOITransType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  29, 'LastCapacity', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  30, 'LastMkt', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  31, 'LastPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  32, 'LastShares', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  33, 'LinesOfText', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  34, 'MsgSeqNum', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  35, 'MsgType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  36, 'NewSeqNo', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  37, 'OrderID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  38, 'OrderQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  39, 'OrdStatus', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  40, 'OrdType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  41, 'OrigClOrdID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  42, 'OrigTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  43, 'PossDupFlag', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  44, 'Price', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  45, 'RefSeqNum', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  46, 'RelatdSym', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  47, 'Rule80A', repeatingHeaderNumber=None, vendor='None', description='Also known as OrderCapacity'),
	FIXTag(  48, 'SecurityID', repeatingHeaderNumber=None, vendor='None', description='Unique instrument ID as qualified by the exchange per tag 22-SecurityIDSource.'),
	FIXTag(  49, 'SenderCompID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  50, 'SenderSubID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  51, 'SendingDate', repeatingHeaderNumber=None, vendor='None', description='No longer used'),
	FIXTag(  52, 'SendingTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  53, 'Shares', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  54, 'Side', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  55, 'Symbol', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  56, 'TargetCompID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  57, 'TargetSubID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  58, 'Text', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  59, 'TimeInForce', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  60, 'TransactTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  61, 'Urgency', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  62, 'ValidUntilTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  63, 'SettlmntTyp', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  64, 'FutSettDate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  65, 'SymbolSfx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  66, 'ListID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  67, 'ListSeqNo', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  68, 'TotNoOrders', repeatingHeaderNumber=None, vendor='None', description='Formerly named ListNoOrds'),
	FIXTag(  69, 'ListExecInst', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  70, 'AllocID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  71, 'AllocTransType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  72, 'RefAllocID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  73, 'NoOrders', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  74, 'AvgPrxPrecision', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  75, 'TradeDate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  76, 'ExecBroker', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  77, 'OpenClose', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  78, 'NoAllocs', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  79, 'AllocAccount', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  80, 'AllocShares', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  81, 'ProcessCode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  82, 'NoRpts', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  83, 'RptSeq', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  84, 'CxlQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  85, 'NoDlvyInst', repeatingHeaderNumber=None, vendor='None', description='No longer used'),
	FIXTag(  86, 'DlvyInst', repeatingHeaderNumber=None, vendor='None', description='No longer used'),
	FIXTag(  87, 'AllocStatus', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  88, 'AllocRejCode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  89, 'Signature', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  90, 'SecureDataLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  91, 'SecureData', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  92, 'BrokerOfCredit', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  93, 'SignatureLength', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  94, 'EmailType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  95, 'RawDataLength', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  96, 'RawData', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  97, 'PossResend', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  98, 'EncryptMethod', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag(  99, 'StopPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 100, 'ExDestination', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 102, 'CxlRejReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 103, 'OrdRejReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 104, 'IOIQualifier', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 105, 'WaveNo', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 106, 'Issuer', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 107, 'SecurityDesc', repeatingHeaderNumber=None, vendor='None', description='Instrument Name.'),
	FIXTag( 108, 'HeartBtInt', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 109, 'ClientID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 110, 'MinQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 111, 'MaxFloor', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 112, 'TestReqID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 113, 'ReportToExch', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 114, 'LocateReqd', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 115, 'OnBehalfOfCompID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 116, 'OnBehalfOfSubID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 117, 'QuoteID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 118, 'NetMoney', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 119, 'SettlCurrAmt', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 120, 'SettlCurrency', repeatingHeaderNumber=None, vendor='None', description='Identifies currency used for settlement price.'),
	FIXTag( 121, 'ForexReq', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 122, 'OrigSendingTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 123, 'GapFillFlag', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 124, 'NoExecs', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 125, 'CxlType', repeatingHeaderNumber=None, vendor='None', description='No longer used'),
	FIXTag( 126, 'ExpireTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 127, 'DKReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 128, 'DeliverToCompID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 129, 'DeliverToSubID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 130, 'IOINaturalFlag', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 131, 'QuoteReqID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 132, 'BidPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 133, 'OfferPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 134, 'BidSize', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 135, 'OfferSize', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 136, 'NoMiscFees', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 137, 'MiscFeeAmt', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 138, 'MiscFeeCurr', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 139, 'MiscFeeType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 140, 'PrevClosePx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 141, 'ResetSeqNumFlag', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 142, 'SenderLocationID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 143, 'TargetLocationID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 144, 'OnBehalfOfLocationID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 145, 'DeliverToLocationID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 146, 'NoRelatedSym', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 147, 'Subject', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 148, 'Headline', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 149, 'URLLink', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 150, 'ExecType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 151, 'LeavesQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 152, 'CashOrderQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 153, 'AllocAvgPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 154, 'AllocNetMoney', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 155, 'SettlCurrFxRate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 156, 'SettlCurrFxRateCalc', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 157, 'NumDaysInterest', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 158, 'AccruedInterestRate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 159, 'AccruedInterestAmt', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 160, 'SettlInstMode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 161, 'AllocText', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 162, 'SettlInstID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 163, 'SettlInstTransType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 164, 'EmailThreadID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 165, 'SettlInstSource', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 166, 'SettlLocation', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 167, 'SecurityType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 168, 'EffectiveTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 169, 'StandInstDbType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 170, 'StandInstDbName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 171, 'StandInstDbID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 172, 'SettlDeliveryType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 173, 'SettlDepositoryCode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 174, 'SettlBrkrCode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 175, 'SettlInstCode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 176, 'SecuritySettlAgentName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 177, 'SecuritySettlAgentCode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 178, 'SecuritySettlAgentAcctNum', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 179, 'SecuritySettlAgentAcctName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 180, 'SecuritySettlAgentContactName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 181, 'SecuritySettlAgentContactPhone', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 182, 'CashSettlAgentName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 183, 'CashSettlAgentCode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 184, 'CashSettlAgentAcctNum', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 185, 'CashSettlAgentAcctName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 186, 'CashSettlAgentContactName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 187, 'CashSettlAgentContactPhone', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 188, 'BidSpotRate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 189, 'BidForwardPoints', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 190, 'OfferSpotRate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 191, 'OfferForwardPoints', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 192, 'OrderQty2', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 193, 'FutSettDate2', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 194, 'LastSpotRate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 195, 'LastForwardPoints', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 196, 'AllocLinkID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 197, 'AllocLinkType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 198, 'SecondaryOrderID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 199, 'NoIOIQualifiers', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 200, 'MaturityMonthYear', repeatingHeaderNumber=None, vendor='None', description='Format YYYYMM (i.e. 200912)'),
	FIXTag( 201, 'PutOrCall', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 202, 'StrikePrice', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 203, 'CoveredOrUncovered', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 204, 'CustomerOrFirm', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 205, 'MaturityDay', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 206, 'OptAttribute', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 207, 'SecurityExchange', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 208, 'NotifyBrokerOfCredit', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 209, 'AllocHandlInst', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 210, 'MaxShow', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 211, 'PegDifference', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 212, 'XmlDataLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 213, 'XmlData', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 214, 'SettlInstRefID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 215, 'NoRoutingIDs', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 216, 'RoutingType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 217, 'RoutingID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 218, 'SpreadToBenchmark', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 219, 'Benchmark', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 223, 'CouponRate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 231, 'ContractMultiplier', repeatingHeaderNumber=None, vendor='None', description='Number of deliverable units per instrument, e.g., peak days in maturity month or number of calendar days in maturity month.'),
	FIXTag( 262, 'MDReqID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 263, 'SubscriptionRequestType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 264, 'MarketDepth', repeatingHeaderNumber=1141, vendor='None', description='Identifies the depth of book.'),
	FIXTag( 265, 'MDUpdateType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 266, 'AggregatedBook', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 267, 'NoMDEntryTypes', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 268, 'NoMDEntries', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 269, 'MDEntryType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 270, 'MDEntryPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 271, 'MDEntrySize', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 272, 'MDEntryDate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 273, 'MDEntryTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 274, 'TickDirection', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 275, 'MDMkt', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 276, 'QuoteCondition', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 277, 'TradeCondition', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 278, 'MDEntryID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 279, 'MDUpdateAction', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 280, 'MDEntryRefID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 281, 'MDReqRejReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 282, 'MDEntryOriginator', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 283, 'LocationID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 284, 'DeskID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 285, 'DeleteReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 286, 'OpenCloseSettleFlag', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 287, 'SellerDays', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 288, 'MDEntryBuyer', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 289, 'MDEntrySeller', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 290, 'MDEntryPositionNo', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 291, 'FinancialStatus', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 292, 'CorporateAction', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 293, 'DefBidSize', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 294, 'DefOfferSize', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 295, 'NoQuoteEntries', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 296, 'NoQuoteSets', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 297, 'QuoteAckStatus', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 298, 'QuoteCancelType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 299, 'QuoteEntryID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 300, 'QuoteRejectReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 301, 'QuoteResponseLevel', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 302, 'QuoteSetID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 303, 'QuoteRequestType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 304, 'TotQuoteEntries', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 305, 'UnderlyingIDSource', repeatingHeaderNumber=711, vendor='None', description='This value is always "8" for CME.'),
	FIXTag( 306, 'UnderlyingIssuer', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 307, 'UnderlyingSecurityDesc', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 308, 'UnderlyingSecurityExchange', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 309, 'UnderlyingSecurityID', repeatingHeaderNumber=711, vendor='None', description='Unique instrument ID as qualified by the exchange per tag 305-UnderlyingSecurityIDSource.'),
	FIXTag( 310, 'UnderlyingSecurityType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 311, 'UnderlyingSymbol', repeatingHeaderNumber=711, vendor='None', description='Underlying security\'s Symbol.'),
	FIXTag( 312, 'UnderlyingSymbolSfx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 313, 'UnderlyingMaturityMonthYear', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 314, 'UnderlyingMaturityDay', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 315, 'UnderlyingPutOrCall', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 316, 'UnderlyingStrikePrice', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 317, 'UnderlyingOptAttribute', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 318, 'Underlying Currency', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 319, 'RatioQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 320, 'SecurityReqID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 321, 'SecurityRequestType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 322, 'SecurityResponseID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 323, 'SecurityResponseType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 324, 'SecurityStatusReqID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 325, 'UnsolicitedIndicator', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 326, 'SecurityTradingStatus', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 327, 'HaltReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 328, 'InViewOfCommon', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 329, 'DueToRelated', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 330, 'BuyVolume', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 331, 'SellVolume', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 332, 'HighPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 333, 'LowPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 334, 'Adjustment', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 335, 'TradSesReqID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 336, 'TradingSessionID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 337, 'ContraTrader', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 338, 'TradSesMethod', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 339, 'TradSesMode', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 340, 'TradSesStatus', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 341, 'TradSesStartTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 342, 'TradSesOpenTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 343, 'TradSesPreCloseTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 344, 'TradSesCloseTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 345, 'TradSesEndTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 346, 'NumberOfOrders', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 347, 'MessageEncoding', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 348, 'EncodedIssuerLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 349, 'EncodedIssuer', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 350, 'EncodedSecurityDescLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 351, 'EncodedSecurityDesc', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 352, 'EncodedListExecInstLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 353, 'EncodedListExecInst', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 354, 'EncodedTextLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 355, 'EncodedText', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 356, 'EncodedSubjectLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 357, 'EncodedSubject', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 358, 'EncodedHeadlineLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 359, 'EncodedHeadline', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 360, 'EncodedAllocTextLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 361, 'EncodedAllocText', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 362, 'EncodedUnderlyingIssuerLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 363, 'EncodedUnderlyingIssuer', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 364, 'EncodedUnderlyingSecurityDescLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 365, 'EncodedUnderlyingSecurityDesc', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 366, 'AllocPrice', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 367, 'QuoteSetValidUntilTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 368, 'QuoteEntryRejectReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 369, 'LastMsgSeqNumProcessed', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 370, 'OnBehalfOfSendingTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 371, 'RefTagID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 372, 'RefMsgType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 373, 'SessionRejectReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 374, 'BidRequestTransType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 375, 'ContraBroker', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 376, 'ComplianceID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 377, 'SolicitedFlag', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 378, 'ExecRestatementReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 379, 'BusinessRejectRefID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 380, 'BusinessRejectReason', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 381, 'GrossTradeAmt', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 382, 'NoContraBrokers', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 383, 'MaxMessageSize', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 384, 'NoMsgTypes', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 385, 'MsgDirection', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 386, 'NoTradingSessions', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 387, 'TotalVolumeTraded', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 388, 'DiscretionInst', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 389, 'DiscretionOffset', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 390, 'BidID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 391, 'ClientBidID', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 392, 'ListName', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 393, 'TotalNumSecurities', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 394, 'BidType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 395, 'NumTickets', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 396, 'SideValue1', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 397, 'SideValue2', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 398, 'NoBidDescriptors', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 399, 'BidDescriptorType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 400, 'BidDescriptor', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 401, 'SideValueInd', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 402, 'LiquidityPctLow', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 403, 'LiquidityPctHigh', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 404, 'LiquidityValue', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 405, 'EFPTrackingError', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 406, 'FairValue', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 407, 'OutsideIndexPct', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 408, 'ValueOfFutures', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 409, 'LiquidityIndType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 410, 'WtAverageLiquidity', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 411, 'ExchangeForPhysical', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 412, 'OutMainCntryUIndex', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 413, 'CrossPercent', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 414, 'ProgRptReqs', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 415, 'ProgPeriodInterval', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 416, 'IncTaxInd', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 417, 'NumBidders', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 418, 'TradeType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 419, 'BasisPxType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 420, 'NoBidComponents', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 421, 'Country', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 422, 'TotNoStrikes', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 423, 'PriceType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 424, 'DayOrderQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 425, 'DayCumQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 426, 'DayAvgPx', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 427, 'GTBookingInst', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 428, 'NoStrikes', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 429, 'ListStatusType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 430, 'NetGrossInd', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 431, 'ListOrderStatus', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 432, 'ExpireDate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 433, 'ListExecInstType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 434, 'CxlRejResponseTo', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 435, 'UnderlyingCouponRate', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 436, 'UnderlyingContractMultiplier', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 437, 'ContraTradeQty', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 438, 'ContraTradeTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 439, 'ClearingFirm', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 440, 'ClearingAccount', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 441, 'LiquidityNumSecurities', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 442, 'MultiLegReportingType', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 443, 'StrikeTime', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 444, 'ListStatusText', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 445, 'EncodedListStatusTextLen', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 446, 'EncodedListStatusText', repeatingHeaderNumber=None, vendor='None', description='None'),
	FIXTag( 454, 'NoSecurityAltID', repeatingHeaderNumber=None, vendor='CME', description='This tag is under development.'),
	FIXTag( 455, 'SecurityAltID', repeatingHeaderNumber=454, vendor='CME', description='This tag is under development.'),
	FIXTag( 456, 'SecurityAltIDSource', repeatingHeaderNumber=454, vendor='CME', description='This tag is under development.'),
	FIXTag( 461, 'CFICode', repeatingHeaderNumber=None, vendor='CME', description='Indicates the type of security using ISO 10962 standard, Classification of Financial Instruments (CFI code) values. See: http://www.cmegroup.com/confluence/display/EPICSANDBOX/Market+Data+-+CFICode+Table+of+Values'),
	FIXTag( 462, 'UnderlyingProduct', repeatingHeaderNumber=None, vendor='CME', description='Product complex (2=Commodity/Agriculture, 4=Currency, 5=Equity, 12=Other, 14=Interest Rate, 15=FX Cash, 16=Energy, 17=Metals)'),
	FIXTag( 555, 'NoLegs', repeatingHeaderNumber=None, vendor='CME', description='Number of legs.'),
	FIXTag( 556, 'LegCurrency', repeatingHeaderNumber=555, vendor='CME', description='Currency for this leg.'),
	FIXTag( 562, 'MinTradeVol', repeatingHeaderNumber=None, vendor='CME', description='The minimum trading volume for a security.'),
	FIXTag( 566, 'LegPrice', repeatingHeaderNumber=555, vendor='CME', description='Price for the futures leg of a covered.'),
	FIXTag( 600, 'LegSymbol', repeatingHeaderNumber=555, vendor='CME', description='Only sent for options strategies and futures spreads. '),
	FIXTag( 602, 'LegSecurityID', repeatingHeaderNumber=555, vendor='CME', description='Unique instrument ID for the leg.'),
	FIXTag( 603, 'LegSecurityIDSource', repeatingHeaderNumber=555, vendor='CME', description='Identifies source of tag 602-LegSecurityID value. This value is always "8" for CME.'),
	FIXTag( 608, 'LegCFICode', repeatingHeaderNumber=555, vendor='CME', description='CFI code for this leg.'),
	FIXTag( 610, 'LegMaturityMonthYear', repeatingHeaderNumber=555, vendor='CME', description='Leg\'s MaturityMonthYear.'),
	FIXTag( 612, 'LegStrikePrice', repeatingHeaderNumber=555, vendor='CME', description='Strike price of the leg.'),
	FIXTag( 616, 'LegSecurityExchange', repeatingHeaderNumber=555, vendor='CME', description='Security exchange of the leg.'),
	FIXTag( 620, 'LegSecurityDesc', repeatingHeaderNumber=555, vendor='CME', description='Leg security description (e.g., ESM0 C1130)'),
	FIXTag( 623, 'LegRatioQty', repeatingHeaderNumber=555, vendor='CME', description='The ratio of quantity for this individual leg relative to the entire multi-leg instrument.'),
	FIXTag( 624, 'LegSide', repeatingHeaderNumber=555, vendor='CME', description='1=Buy, 2=Sell.'),
	FIXTag( 711, 'NoUnderlyings', repeatingHeaderNumber=None, vendor='CME', description='Number of underlying instruments.'),
	FIXTag( 731, 'SettlPriceType', repeatingHeaderNumber=None, vendor='CME', description='Indicates whether settlement price is preliminary or final (1=Final, 2=Theoretical, 100=Actual preliminary for instruments not subject to rounding, 101=Actual preliminary for instruments subject to rounding).'),
	FIXTag( 762, 'SecuritySubType', repeatingHeaderNumber=None, vendor='CME', description='Indicates Strategy type.'),
	FIXTag( 764, 'LegSecuritySubType', repeatingHeaderNumber=555, vendor='CME', description='If leg repeating group is a spread, the strategy type for the spread.'),
	FIXTag( 779, 'LastUpdateTime', repeatingHeaderNumber=None, vendor='CME', description='Timestamp of when the instrument was deleted.'),
	FIXTag( 827, 'ExpirationCycle', repeatingHeaderNumber=None, vendor='CME', description='Indicates if the instrument expires at the trading session close, or at a specified last eligible trade date. If 0, the instrument is eligible for Day orders only. If 2, the instrument is eligible for GTC/GTD orders (outrights only). '),
	FIXTag( 864, 'NoEvents', repeatingHeaderNumber=None, vendor='CME', description='Number of repeating EventType entries.'),
	FIXTag( 865, 'EventType', repeatingHeaderNumber=864, vendor='CME', description='Code to represent the type of event (5=Activation, 7=Last eligible trade date)'),
	FIXTag( 866, 'EventDate', repeatingHeaderNumber=864, vendor='CME', description='Date of event.'),
	FIXTag( 870, 'NbInstAttrib', repeatingHeaderNumber=None, vendor='CME', description='Number of repeating group InstrAttribType entries.'),
	FIXTag( 871, 'InstAttribType', repeatingHeaderNumber=870, vendor='CME', description='Tag 871-InstAttribType and tag 872-InstAttribValue function together where tag 871 indicates the type of value that the following tag 872 will contain.'),
	FIXTag( 872, 'InstAttribValue', repeatingHeaderNumber=870, vendor='CME', description='Tag 871-InstAttribType and tag 872-InstAttribValue function together where tag 871 indicates the type of value that the following tag 872 will contain.'),
	FIXTag( 911, 'TotNumReports', repeatingHeaderNumber=None, vendor='CME', description='Total number of reports returned in response to a request.'),
	FIXTag( 942, 'LegStrikeCurrency', repeatingHeaderNumber=555, vendor='CME', description='Currency of the strike price of the leg.'),
	FIXTag( 947, 'StrikeCurrency', repeatingHeaderNumber=None, vendor='CME', description='Currency in which the strike price is denominated.'),
	FIXTag( 969, 'MinPriceIncrement', repeatingHeaderNumber=None, vendor='CME', description='Minimum constant tick for the instrument, sent only if instrument is non-VTT (Variable Tick table) eligible.'),
	FIXTag( 980, 'SecurityUpdateAction', repeatingHeaderNumber=None, vendor='CME', description='M=Modify, D=Delete.'),
	FIXTag( 996, 'UnitOfMeasure', repeatingHeaderNumber=None, vendor='CME', description='Unit of measure for the products\' original contract size.'),
	FIXTag(1017, 'LegOptionDelta', repeatingHeaderNumber=555, vendor='CME', description='Delta used to calculate the quantity of futures used to cover the option or option strategy.'),
	FIXTag(1022, 'MDFeedType', repeatingHeaderNumber=1141, vendor='CME', description='Describes a class of service for a given data feed.'),
	FIXTag(1093, 'LotType', repeatingHeaderNumber=1234, vendor='CME', description='The quantity type used for the leg of the spread. This tag is required to interpret the value in tag 1231-MinLotSize.'),
	FIXTag(1140, 'MaxTradeVol', repeatingHeaderNumber=None, vendor='CME', description='The maximum trading volume for a security.'),
	FIXTag(1141, 'NoMdFeedTypes', repeatingHeaderNumber=None, vendor='CME', description='Number of repeating FeedType repeating group entries.'),
	FIXTag(1142, 'MatchingAlgorithm', repeatingHeaderNumber=None, vendor='CME', description='Matching algorithm (F=FIFO, K=Configurable, C=Pro-Rata, A=Allocation, T=FIFO with LLM, O=Threshold Pro-Rata, S=FIFO with TOP and LLM, Q=Threshold Pro-Rata with LLM, Y=Eurodollar options)'),
	FIXTag(1143, 'MaxPriceVariation', repeatingHeaderNumber=None, vendor='CME', description='Differential value for price banding.'),
	FIXTag(1144, 'ImpliedMarketIndicator', repeatingHeaderNumber=None, vendor='CME', description='Informs the market that an instrument is eligible for implied trading (Implied In & Out; 0=Non-implied, 3=Implied). If this tag is not present, instrument is non-implied.'),
	FIXTag(1145, 'EventTime', repeatingHeaderNumber=864, vendor='CME', description='Time of event.'),
	FIXTag(1146, 'MinPriceIncrementAmount', repeatingHeaderNumber=None, vendor='CME', description='Under development.'),
	FIXTag(1147, 'UnitOfMeasureQty', repeatingHeaderNumber=None, vendor='CME', description='This field contains the contract size for each instrument (in combination with tag 996).'),
	FIXTag(1148, 'LowLimitPrice', repeatingHeaderNumber=None, vendor='CME', description='Lower price threshold for the instrument. Orders submitted with prices below the lower limit will be rejected.'),
	FIXTag(1149, 'HighLimitPrice', repeatingHeaderNumber=None, vendor='CME', description='Upper price threshold for the instrument. Orders submitted with prices above the upper limit will be rejected.'),
	FIXTag(1150, 'TradingReferencePrice', repeatingHeaderNumber=None, vendor='CME', description='The most recent settlement price.'),
	FIXTag(1151, 'SecurityGroup', repeatingHeaderNumber=None, vendor='CME', description='Product code.'),
	FIXTag(1180, 'AppIID', repeatingHeaderNumber=None, vendor='CME', description='The channel ID as defined in the XML Configuration file.'),
	FIXTag(1234, 'NoLotTypeRules', repeatingHeaderNumber=None, vendor='CME', description='Number of quantity types in the upcoming repeating group.'),
	FIXTag(1300, 'MarketSegmentID', repeatingHeaderNumber=None, vendor='CME', description='Identifies the market segment.'),
	FIXTag(1435, 'ContractMultiplierUnit', repeatingHeaderNumber=None, vendor='CME', description='Indicates the type of multiplier being applied to the product. Used in combination with tag 231. 1=Hour, 2=Day'),
	FIXTag(1439, 'FlowScheduleType', repeatingHeaderNumber=None, vendor='CME', description='The schedule according to which the electricity is delivered in a physical contract, or priced in a financial contract. '),
	FIXTag(5770, 'PriceRatio', repeatingHeaderNumber=None, vendor='CME', description='Used for price calculation in spread and leg pricing.'),
	FIXTag(5791, 'ClearedVolume', repeatingHeaderNumber=None, vendor='CME', description='Indicates the total cleared volume of instruments traded during the prior trading session.'),
	FIXTag(5792, 'OpenInterestQty', repeatingHeaderNumber=None, vendor='CME', description='Indicates the total open interest for the market at the close of the prior trading session.'),
	FIXTag(5795, 'LegSecurityGroup', repeatingHeaderNumber=555, vendor='CME', description='Product code for this leg.'),
	FIXTag(5796, 'TradingReferenceDate', repeatingHeaderNumber=None, vendor='CME', description='Indicates the date the last update to the settlement price.'),
	FIXTag(5818, 'DecayQty', repeatingHeaderNumber=None, vendor='CME', description='Indicates the quantity that a contract will decay daily by once the decay start date is reached.'),
	FIXTag(5819, 'DecayStartDate', repeatingHeaderNumber=None, vendor='CME', description='Indicates the date at which a decay contract will begin to decay.'),
	FIXTag(5849, 'OriginalContractSize', repeatingHeaderNumber=None, vendor='CME', description='Fixed contract value assigned to a product.'),
	FIXTag(9779, 'UserDefinedInstrument', repeatingHeaderNumber=None, vendor='CME', description='Y=User defined, N=Not.'),
	FIXTag(9787, 'DisplayFactor', repeatingHeaderNumber=None, vendor='CME', description='Contains the multiplier to convert the CME Globex display price to the conventional price.'),
	FIXTag(9850, 'MinCabPrice', repeatingHeaderNumber=None, vendor='CME', description='Defines cabinet price for outright options products.'),
	FIXTag(9853, 'PricingModel', repeatingHeaderNumber=None, vendor='CME', description='Identifies options pricing model (F=Fischer-Black, W=Whaley).'),
]

TAG_ID_TO_NAME = {}
TAG_NAME_TO_ID = {}
for tag in TAGS:
	assert(tag.id() not in TAG_ID_TO_NAME)
	TAG_ID_TO_NAME[tag.id()] = tag

	assert(tag.name() not in TAG_NAME_TO_ID)
	TAG_NAME_TO_ID[tag.name()] = tag

