
from .Protocol import FIXTag

TAGS = [
##### BEGIN GENERATED CODE
	FIXTag(   1, 'Account', repeatingHeaderId=None, vendor=None),
	FIXTag(   2, 'AdvId', repeatingHeaderId=None, vendor=None),
	FIXTag(   3, 'AdvRefID', repeatingHeaderId=None, vendor=None),
	FIXTag(   4, 'AdvSide', repeatingHeaderId=None, vendor=None),
	FIXTag(   5, 'AdvTransType', repeatingHeaderId=None, vendor=None),
	FIXTag(   6, 'AvgPx', repeatingHeaderId=None, vendor=None),
	FIXTag(   7, 'BeginSeqNo', repeatingHeaderId=None, vendor=None),
	FIXTag(   8, 'BeginString', repeatingHeaderId=None, vendor=None),
	FIXTag(   9, 'BodyLength', repeatingHeaderId=None, vendor=None),
	FIXTag(  10, 'CheckSum', repeatingHeaderId=None, vendor=None),
	FIXTag(  11, 'ClOrdID', repeatingHeaderId=None, vendor=None),
	FIXTag(  12, 'Commission', repeatingHeaderId=None, vendor=None),
	FIXTag(  13, 'CommType', repeatingHeaderId=None, vendor=None),
	FIXTag(  14, 'CumQty', repeatingHeaderId=None, vendor=None),
	FIXTag(  15, 'Currency', repeatingHeaderId=None, vendor=None, description='Identifies currency used for price.'),
	FIXTag(  16, 'EndSeqNo', repeatingHeaderId=None, vendor=None),
	FIXTag(  17, 'ExecID', repeatingHeaderId=None, vendor=None),
	FIXTag(  18, 'ExecInst', repeatingHeaderId=None, vendor=None),
	FIXTag(  19, 'ExecRefID', repeatingHeaderId=None, vendor=None),
	FIXTag(  20, 'ExecTransType', repeatingHeaderId=None, vendor=None),
	FIXTag(  21, 'HandlInst', repeatingHeaderId=None, vendor=None),
	FIXTag(  22, 'IDSource', repeatingHeaderId=None, vendor=None),
	FIXTag(  23, 'IOIid', repeatingHeaderId=None, vendor=None),
	FIXTag(  24, 'IOIOthSvc', repeatingHeaderId=None, vendor=None, description='No longer used'),
	FIXTag(  25, 'IOIQltyInd', repeatingHeaderId=None, vendor=None),
	FIXTag(  26, 'IOIRefID', repeatingHeaderId=None, vendor=None),
	FIXTag(  27, 'IOIShares', repeatingHeaderId=None, vendor=None),
	FIXTag(  28, 'IOITransType', repeatingHeaderId=None, vendor=None),
	FIXTag(  29, 'LastCapacity', repeatingHeaderId=None, vendor=None),
	FIXTag(  30, 'LastMkt', repeatingHeaderId=None, vendor=None),
	FIXTag(  31, 'LastPx', repeatingHeaderId=None, vendor=None),
	FIXTag(  32, 'LastShares', repeatingHeaderId=None, vendor=None),
	FIXTag(  33, 'LinesOfText', repeatingHeaderId=None, vendor=None),
	FIXTag(  34, 'MsgSeqNum', repeatingHeaderId=None, vendor=None),
	FIXTag(  35, 'MsgType', repeatingHeaderId=None, vendor=None),
	FIXTag(  36, 'NewSeqNo', repeatingHeaderId=None, vendor=None),
	FIXTag(  37, 'OrderID', repeatingHeaderId=None, vendor=None),
	FIXTag(  38, 'OrderQty', repeatingHeaderId=None, vendor=None),
	FIXTag(  39, 'OrdStatus', repeatingHeaderId=None, vendor=None),
	FIXTag(  40, 'OrdType', repeatingHeaderId=None, vendor=None),
	FIXTag(  41, 'OrigClOrdID', repeatingHeaderId=None, vendor=None),
	FIXTag(  42, 'OrigTime', repeatingHeaderId=None, vendor=None),
	FIXTag(  43, 'PossDupFlag', repeatingHeaderId=None, vendor=None),
	FIXTag(  44, 'Price', repeatingHeaderId=None, vendor=None),
	FIXTag(  45, 'RefSeqNum', repeatingHeaderId=None, vendor=None),
	FIXTag(  46, 'RelatdSym', repeatingHeaderId=None, vendor=None),
	FIXTag(  47, 'Rule80A', repeatingHeaderId=None, vendor=None, description='Also known as OrderCapacity'),
	FIXTag(  48, 'SecurityID', repeatingHeaderId=None, vendor=None, description='Unique instrument ID as qualified by the exchange per tag 22-SecurityIDSource.'),
	FIXTag(  49, 'SenderCompID', repeatingHeaderId=None, vendor=None),
	FIXTag(  50, 'SenderSubID', repeatingHeaderId=None, vendor=None),
	FIXTag(  51, 'SendingDate', repeatingHeaderId=None, vendor=None, description='No longer used'),
	FIXTag(  52, 'SendingTime', repeatingHeaderId=None, vendor=None),
	FIXTag(  53, 'Shares', repeatingHeaderId=None, vendor=None),
	FIXTag(  54, 'Side', repeatingHeaderId=None, vendor=None),
	FIXTag(  55, 'Symbol', repeatingHeaderId=None, vendor=None),
	FIXTag(  56, 'TargetCompID', repeatingHeaderId=None, vendor=None),
	FIXTag(  57, 'TargetSubID', repeatingHeaderId=None, vendor=None),
	FIXTag(  58, 'Text', repeatingHeaderId=None, vendor=None),
	FIXTag(  59, 'TimeInForce', repeatingHeaderId=None, vendor=None),
	FIXTag(  60, 'TransactTime', repeatingHeaderId=None, vendor=None),
	FIXTag(  61, 'Urgency', repeatingHeaderId=None, vendor=None),
	FIXTag(  62, 'ValidUntilTime', repeatingHeaderId=None, vendor=None),
	FIXTag(  63, 'SettlmntTyp', repeatingHeaderId=None, vendor=None),
	FIXTag(  64, 'FutSettDate', repeatingHeaderId=None, vendor=None),
	FIXTag(  65, 'SymbolSfx', repeatingHeaderId=None, vendor=None),
	FIXTag(  66, 'ListID', repeatingHeaderId=None, vendor=None),
	FIXTag(  67, 'ListSeqNo', repeatingHeaderId=None, vendor=None),
	FIXTag(  68, 'TotNoOrders', repeatingHeaderId=None, vendor=None, description='Formerly named ListNoOrds'),
	FIXTag(  69, 'ListExecInst', repeatingHeaderId=None, vendor=None),
	FIXTag(  70, 'AllocID', repeatingHeaderId=None, vendor=None),
	FIXTag(  71, 'AllocTransType', repeatingHeaderId=None, vendor=None),
	FIXTag(  72, 'RefAllocID', repeatingHeaderId=None, vendor=None),
	FIXTag(  73, 'NoOrders', repeatingHeaderId=None, vendor=None),
	FIXTag(  74, 'AvgPrxPrecision', repeatingHeaderId=None, vendor=None),
	FIXTag(  75, 'TradeDate', repeatingHeaderId=None, vendor=None),
	FIXTag(  76, 'ExecBroker', repeatingHeaderId=None, vendor=None),
	FIXTag(  77, 'OpenClose', repeatingHeaderId=None, vendor=None),
	FIXTag(  78, 'NoAllocs', repeatingHeaderId=None, vendor=None),
	FIXTag(  79, 'AllocAccount', repeatingHeaderId=None, vendor=None),
	FIXTag(  80, 'AllocShares', repeatingHeaderId=None, vendor=None),
	FIXTag(  81, 'ProcessCode', repeatingHeaderId=None, vendor=None),
	FIXTag(  82, 'NoRpts', repeatingHeaderId=None, vendor=None),
	FIXTag(  83, 'RptSeq', repeatingHeaderId=None, vendor=None),
	FIXTag(  84, 'CxlQty', repeatingHeaderId=None, vendor=None),
	FIXTag(  85, 'NoDlvyInst', repeatingHeaderId=None, vendor=None, description='No longer used'),
	FIXTag(  86, 'DlvyInst', repeatingHeaderId=None, vendor=None, description='No longer used'),
	FIXTag(  87, 'AllocStatus', repeatingHeaderId=None, vendor=None),
	FIXTag(  88, 'AllocRejCode', repeatingHeaderId=None, vendor=None),
	FIXTag(  89, 'Signature', repeatingHeaderId=None, vendor=None),
	FIXTag(  90, 'SecureDataLen', repeatingHeaderId=None, vendor=None),
	FIXTag(  91, 'SecureData', repeatingHeaderId=None, vendor=None),
	FIXTag(  92, 'BrokerOfCredit', repeatingHeaderId=None, vendor=None),
	FIXTag(  93, 'SignatureLength', repeatingHeaderId=None, vendor=None),
	FIXTag(  94, 'EmailType', repeatingHeaderId=None, vendor=None),
	FIXTag(  95, 'RawDataLength', repeatingHeaderId=None, vendor=None),
	FIXTag(  96, 'RawData', repeatingHeaderId=None, vendor=None),
	FIXTag(  97, 'PossResend', repeatingHeaderId=None, vendor=None),
	FIXTag(  98, 'EncryptMethod', repeatingHeaderId=None, vendor=None),
	FIXTag(  99, 'StopPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 100, 'ExDestination', repeatingHeaderId=None, vendor=None),
	FIXTag( 102, 'CxlRejReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 103, 'OrdRejReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 104, 'IOIQualifier', repeatingHeaderId=None, vendor=None),
	FIXTag( 105, 'WaveNo', repeatingHeaderId=None, vendor=None),
	FIXTag( 106, 'Issuer', repeatingHeaderId=None, vendor=None),
	FIXTag( 107, 'SecurityDesc', repeatingHeaderId=None, vendor=None, description='Instrument Name.'),
	FIXTag( 108, 'HeartBtInt', repeatingHeaderId=None, vendor=None),
	FIXTag( 109, 'ClientID', repeatingHeaderId=None, vendor=None),
	FIXTag( 110, 'MinQty', repeatingHeaderId=None, vendor=None),
	FIXTag( 111, 'MaxFloor', repeatingHeaderId=None, vendor=None),
	FIXTag( 112, 'TestReqID', repeatingHeaderId=None, vendor=None),
	FIXTag( 113, 'ReportToExch', repeatingHeaderId=None, vendor=None),
	FIXTag( 114, 'LocateReqd', repeatingHeaderId=None, vendor=None),
	FIXTag( 115, 'OnBehalfOfCompID', repeatingHeaderId=None, vendor=None),
	FIXTag( 116, 'OnBehalfOfSubID', repeatingHeaderId=None, vendor=None),
	FIXTag( 117, 'QuoteID', repeatingHeaderId=None, vendor=None),
	FIXTag( 118, 'NetMoney', repeatingHeaderId=None, vendor=None),
	FIXTag( 119, 'SettlCurrAmt', repeatingHeaderId=None, vendor=None),
	FIXTag( 120, 'SettlCurrency', repeatingHeaderId=None, vendor=None, description='Identifies currency used for settlement price.'),
	FIXTag( 121, 'ForexReq', repeatingHeaderId=None, vendor=None),
	FIXTag( 122, 'OrigSendingTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 123, 'GapFillFlag', repeatingHeaderId=None, vendor=None),
	FIXTag( 124, 'NoExecs', repeatingHeaderId=None, vendor=None),
	FIXTag( 125, 'CxlType', repeatingHeaderId=None, vendor=None, description='No longer used'),
	FIXTag( 126, 'ExpireTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 127, 'DKReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 128, 'DeliverToCompID', repeatingHeaderId=None, vendor=None),
	FIXTag( 129, 'DeliverToSubID', repeatingHeaderId=None, vendor=None),
	FIXTag( 130, 'IOINaturalFlag', repeatingHeaderId=None, vendor=None),
	FIXTag( 131, 'QuoteReqID', repeatingHeaderId=None, vendor=None),
	FIXTag( 132, 'BidPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 133, 'OfferPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 134, 'BidSize', repeatingHeaderId=None, vendor=None),
	FIXTag( 135, 'OfferSize', repeatingHeaderId=None, vendor=None),
	FIXTag( 136, 'NoMiscFees', repeatingHeaderId=None, vendor=None),
	FIXTag( 137, 'MiscFeeAmt', repeatingHeaderId=None, vendor=None),
	FIXTag( 138, 'MiscFeeCurr', repeatingHeaderId=None, vendor=None),
	FIXTag( 139, 'MiscFeeType', repeatingHeaderId=None, vendor=None),
	FIXTag( 140, 'PrevClosePx', repeatingHeaderId=None, vendor=None),
	FIXTag( 141, 'ResetSeqNumFlag', repeatingHeaderId=None, vendor=None),
	FIXTag( 142, 'SenderLocationID', repeatingHeaderId=None, vendor=None),
	FIXTag( 143, 'TargetLocationID', repeatingHeaderId=None, vendor=None),
	FIXTag( 144, 'OnBehalfOfLocationID', repeatingHeaderId=None, vendor=None),
	FIXTag( 145, 'DeliverToLocationID', repeatingHeaderId=None, vendor=None),
	FIXTag( 146, 'NoRelatedSym', repeatingHeaderId=None, vendor=None),
	FIXTag( 147, 'Subject', repeatingHeaderId=None, vendor=None),
	FIXTag( 148, 'Headline', repeatingHeaderId=None, vendor=None),
	FIXTag( 149, 'URLLink', repeatingHeaderId=None, vendor=None),
	FIXTag( 150, 'ExecType', repeatingHeaderId=None, vendor=None),
	FIXTag( 151, 'LeavesQty', repeatingHeaderId=None, vendor=None),
	FIXTag( 152, 'CashOrderQty', repeatingHeaderId=None, vendor=None),
	FIXTag( 153, 'AllocAvgPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 154, 'AllocNetMoney', repeatingHeaderId=None, vendor=None),
	FIXTag( 155, 'SettlCurrFxRate', repeatingHeaderId=None, vendor=None),
	FIXTag( 156, 'SettlCurrFxRateCalc', repeatingHeaderId=None, vendor=None),
	FIXTag( 157, 'NumDaysInterest', repeatingHeaderId=None, vendor=None),
	FIXTag( 158, 'AccruedInterestRate', repeatingHeaderId=None, vendor=None),
	FIXTag( 159, 'AccruedInterestAmt', repeatingHeaderId=None, vendor=None),
	FIXTag( 160, 'SettlInstMode', repeatingHeaderId=None, vendor=None),
	FIXTag( 161, 'AllocText', repeatingHeaderId=None, vendor=None),
	FIXTag( 162, 'SettlInstID', repeatingHeaderId=None, vendor=None),
	FIXTag( 163, 'SettlInstTransType', repeatingHeaderId=None, vendor=None),
	FIXTag( 164, 'EmailThreadID', repeatingHeaderId=None, vendor=None),
	FIXTag( 165, 'SettlInstSource', repeatingHeaderId=None, vendor=None),
	FIXTag( 166, 'SettlLocation', repeatingHeaderId=None, vendor=None),
	FIXTag( 167, 'SecurityType', repeatingHeaderId=None, vendor=None),
	FIXTag( 168, 'EffectiveTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 169, 'StandInstDbType', repeatingHeaderId=None, vendor=None),
	FIXTag( 170, 'StandInstDbName', repeatingHeaderId=None, vendor=None),
	FIXTag( 171, 'StandInstDbID', repeatingHeaderId=None, vendor=None),
	FIXTag( 172, 'SettlDeliveryType', repeatingHeaderId=None, vendor=None),
	FIXTag( 173, 'SettlDepositoryCode', repeatingHeaderId=None, vendor=None),
	FIXTag( 174, 'SettlBrkrCode', repeatingHeaderId=None, vendor=None),
	FIXTag( 175, 'SettlInstCode', repeatingHeaderId=None, vendor=None),
	FIXTag( 176, 'SecuritySettlAgentName', repeatingHeaderId=None, vendor=None),
	FIXTag( 177, 'SecuritySettlAgentCode', repeatingHeaderId=None, vendor=None),
	FIXTag( 178, 'SecuritySettlAgentAcctNum', repeatingHeaderId=None, vendor=None),
	FIXTag( 179, 'SecuritySettlAgentAcctName', repeatingHeaderId=None, vendor=None),
	FIXTag( 180, 'SecuritySettlAgentContactName', repeatingHeaderId=None, vendor=None),
	FIXTag( 181, 'SecuritySettlAgentContactPhone', repeatingHeaderId=None, vendor=None),
	FIXTag( 182, 'CashSettlAgentName', repeatingHeaderId=None, vendor=None),
	FIXTag( 183, 'CashSettlAgentCode', repeatingHeaderId=None, vendor=None),
	FIXTag( 184, 'CashSettlAgentAcctNum', repeatingHeaderId=None, vendor=None),
	FIXTag( 185, 'CashSettlAgentAcctName', repeatingHeaderId=None, vendor=None),
	FIXTag( 186, 'CashSettlAgentContactName', repeatingHeaderId=None, vendor=None),
	FIXTag( 187, 'CashSettlAgentContactPhone', repeatingHeaderId=None, vendor=None),
	FIXTag( 188, 'BidSpotRate', repeatingHeaderId=None, vendor=None),
	FIXTag( 189, 'BidForwardPoints', repeatingHeaderId=None, vendor=None),
	FIXTag( 190, 'OfferSpotRate', repeatingHeaderId=None, vendor=None),
	FIXTag( 191, 'OfferForwardPoints', repeatingHeaderId=None, vendor=None),
	FIXTag( 192, 'OrderQty2', repeatingHeaderId=None, vendor=None),
	FIXTag( 193, 'FutSettDate2', repeatingHeaderId=None, vendor=None),
	FIXTag( 194, 'LastSpotRate', repeatingHeaderId=None, vendor=None),
	FIXTag( 195, 'LastForwardPoints', repeatingHeaderId=None, vendor=None),
	FIXTag( 196, 'AllocLinkID', repeatingHeaderId=None, vendor=None),
	FIXTag( 197, 'AllocLinkType', repeatingHeaderId=None, vendor=None),
	FIXTag( 198, 'SecondaryOrderID', repeatingHeaderId=None, vendor=None),
	FIXTag( 199, 'NoIOIQualifiers', repeatingHeaderId=None, vendor=None),
	FIXTag( 200, 'MaturityMonthYear', repeatingHeaderId=None, vendor=None, description='Format YYYYMM (i.e. 200912)'),
	FIXTag( 201, 'PutOrCall', repeatingHeaderId=None, vendor=None),
	FIXTag( 202, 'StrikePrice', repeatingHeaderId=None, vendor=None),
	FIXTag( 203, 'CoveredOrUncovered', repeatingHeaderId=None, vendor=None),
	FIXTag( 204, 'CustomerOrFirm', repeatingHeaderId=None, vendor=None),
	FIXTag( 205, 'MaturityDay', repeatingHeaderId=None, vendor=None),
	FIXTag( 206, 'OptAttribute', repeatingHeaderId=None, vendor=None),
	FIXTag( 207, 'SecurityExchange', repeatingHeaderId=None, vendor=None),
	FIXTag( 208, 'NotifyBrokerOfCredit', repeatingHeaderId=None, vendor=None),
	FIXTag( 209, 'AllocHandlInst', repeatingHeaderId=None, vendor=None),
	FIXTag( 210, 'MaxShow', repeatingHeaderId=None, vendor=None),
	FIXTag( 211, 'PegDifference', repeatingHeaderId=None, vendor=None),
	FIXTag( 212, 'XmlDataLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 213, 'XmlData', repeatingHeaderId=None, vendor=None),
	FIXTag( 214, 'SettlInstRefID', repeatingHeaderId=None, vendor=None),
	FIXTag( 215, 'NoRoutingIDs', repeatingHeaderId=None, vendor=None),
	FIXTag( 216, 'RoutingType', repeatingHeaderId=None, vendor=None),
	FIXTag( 217, 'RoutingID', repeatingHeaderId=None, vendor=None),
	FIXTag( 218, 'SpreadToBenchmark', repeatingHeaderId=None, vendor=None),
	FIXTag( 219, 'Benchmark', repeatingHeaderId=None, vendor=None),
	FIXTag( 223, 'CouponRate', repeatingHeaderId=None, vendor=None),
	FIXTag( 231, 'ContractMultiplier', repeatingHeaderId=None, vendor=None, description='Number of deliverable units per instrument, e.g., peak days in maturity month or number of calendar days in maturity month.'),
	FIXTag( 262, 'MDReqID', repeatingHeaderId=None, vendor=None),
	FIXTag( 263, 'SubscriptionRequestType', repeatingHeaderId=None, vendor=None),
	FIXTag( 264, 'MarketDepth', repeatingHeaderId=1141, vendor=None, description='Identifies the depth of book.'),
	FIXTag( 265, 'MDUpdateType', repeatingHeaderId=None, vendor=None),
	FIXTag( 266, 'AggregatedBook', repeatingHeaderId=None, vendor=None),
	FIXTag( 267, 'NoMDEntryTypes', repeatingHeaderId=None, vendor=None),
	FIXTag( 268, 'NoMDEntries', repeatingHeaderId=None, vendor=None),
	FIXTag( 269, 'MDEntryType', repeatingHeaderId=None, vendor=None),
	FIXTag( 270, 'MDEntryPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 271, 'MDEntrySize', repeatingHeaderId=None, vendor=None),
	FIXTag( 272, 'MDEntryDate', repeatingHeaderId=None, vendor=None),
	FIXTag( 273, 'MDEntryTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 274, 'TickDirection', repeatingHeaderId=None, vendor=None),
	FIXTag( 275, 'MDMkt', repeatingHeaderId=None, vendor=None),
	FIXTag( 276, 'QuoteCondition', repeatingHeaderId=None, vendor=None),
	FIXTag( 277, 'TradeCondition', repeatingHeaderId=None, vendor=None),
	FIXTag( 278, 'MDEntryID', repeatingHeaderId=None, vendor=None),
	FIXTag( 279, 'MDUpdateAction', repeatingHeaderId=None, vendor=None),
	FIXTag( 280, 'MDEntryRefID', repeatingHeaderId=None, vendor=None),
	FIXTag( 281, 'MDReqRejReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 282, 'MDEntryOriginator', repeatingHeaderId=None, vendor=None),
	FIXTag( 283, 'LocationID', repeatingHeaderId=None, vendor=None),
	FIXTag( 284, 'DeskID', repeatingHeaderId=None, vendor=None),
	FIXTag( 285, 'DeleteReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 286, 'OpenCloseSettleFlag', repeatingHeaderId=None, vendor=None),
	FIXTag( 287, 'SellerDays', repeatingHeaderId=None, vendor=None),
	FIXTag( 288, 'MDEntryBuyer', repeatingHeaderId=None, vendor=None),
	FIXTag( 289, 'MDEntrySeller', repeatingHeaderId=None, vendor=None),
	FIXTag( 290, 'MDEntryPositionNo', repeatingHeaderId=None, vendor=None),
	FIXTag( 291, 'FinancialStatus', repeatingHeaderId=None, vendor=None),
	FIXTag( 292, 'CorporateAction', repeatingHeaderId=None, vendor=None),
	FIXTag( 293, 'DefBidSize', repeatingHeaderId=None, vendor=None),
	FIXTag( 294, 'DefOfferSize', repeatingHeaderId=None, vendor=None),
	FIXTag( 295, 'NoQuoteEntries', repeatingHeaderId=None, vendor=None),
	FIXTag( 296, 'NoQuoteSets', repeatingHeaderId=None, vendor=None),
	FIXTag( 297, 'QuoteAckStatus', repeatingHeaderId=None, vendor=None),
	FIXTag( 298, 'QuoteCancelType', repeatingHeaderId=None, vendor=None),
	FIXTag( 299, 'QuoteEntryID', repeatingHeaderId=None, vendor=None),
	FIXTag( 300, 'QuoteRejectReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 301, 'QuoteResponseLevel', repeatingHeaderId=None, vendor=None),
	FIXTag( 302, 'QuoteSetID', repeatingHeaderId=None, vendor=None),
	FIXTag( 303, 'QuoteRequestType', repeatingHeaderId=None, vendor=None),
	FIXTag( 304, 'TotQuoteEntries', repeatingHeaderId=None, vendor=None),
	FIXTag( 305, 'UnderlyingIDSource', repeatingHeaderId=711, vendor=None, description="This value is always '8' for CME."),
	FIXTag( 306, 'UnderlyingIssuer', repeatingHeaderId=None, vendor=None),
	FIXTag( 307, 'UnderlyingSecurityDesc', repeatingHeaderId=None, vendor=None),
	FIXTag( 308, 'UnderlyingSecurityExchange', repeatingHeaderId=None, vendor=None),
	FIXTag( 309, 'UnderlyingSecurityID', repeatingHeaderId=711, vendor=None, description='Unique instrument ID as qualified by the exchange per tag 305-UnderlyingSecurityIDSource.'),
	FIXTag( 310, 'UnderlyingSecurityType', repeatingHeaderId=None, vendor=None),
	FIXTag( 311, 'UnderlyingSymbol', repeatingHeaderId=711, vendor=None, description="Underlying security's Symbol."),
	FIXTag( 312, 'UnderlyingSymbolSfx', repeatingHeaderId=None, vendor=None),
	FIXTag( 313, 'UnderlyingMaturityMonthYear', repeatingHeaderId=None, vendor=None),
	FIXTag( 314, 'UnderlyingMaturityDay', repeatingHeaderId=None, vendor=None),
	FIXTag( 315, 'UnderlyingPutOrCall', repeatingHeaderId=None, vendor=None),
	FIXTag( 316, 'UnderlyingStrikePrice', repeatingHeaderId=None, vendor=None),
	FIXTag( 317, 'UnderlyingOptAttribute', repeatingHeaderId=None, vendor=None),
	FIXTag( 318, 'Underlying Currency', repeatingHeaderId=None, vendor=None),
	FIXTag( 319, 'RatioQty', repeatingHeaderId=None, vendor=None),
	FIXTag( 320, 'SecurityReqID', repeatingHeaderId=None, vendor=None),
	FIXTag( 321, 'SecurityRequestType', repeatingHeaderId=None, vendor=None),
	FIXTag( 322, 'SecurityResponseID', repeatingHeaderId=None, vendor=None),
	FIXTag( 323, 'SecurityResponseType', repeatingHeaderId=None, vendor=None),
	FIXTag( 324, 'SecurityStatusReqID', repeatingHeaderId=None, vendor=None),
	FIXTag( 325, 'UnsolicitedIndicator', repeatingHeaderId=None, vendor=None),
	FIXTag( 326, 'SecurityTradingStatus', repeatingHeaderId=None, vendor=None),
	FIXTag( 327, 'HaltReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 328, 'InViewOfCommon', repeatingHeaderId=None, vendor=None),
	FIXTag( 329, 'DueToRelated', repeatingHeaderId=None, vendor=None),
	FIXTag( 330, 'BuyVolume', repeatingHeaderId=None, vendor=None),
	FIXTag( 331, 'SellVolume', repeatingHeaderId=None, vendor=None),
	FIXTag( 332, 'HighPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 333, 'LowPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 334, 'Adjustment', repeatingHeaderId=None, vendor=None),
	FIXTag( 335, 'TradSesReqID', repeatingHeaderId=None, vendor=None),
	FIXTag( 336, 'TradingSessionID', repeatingHeaderId=None, vendor=None),
	FIXTag( 337, 'ContraTrader', repeatingHeaderId=None, vendor=None),
	FIXTag( 338, 'TradSesMethod', repeatingHeaderId=None, vendor=None),
	FIXTag( 339, 'TradSesMode', repeatingHeaderId=None, vendor=None),
	FIXTag( 340, 'TradSesStatus', repeatingHeaderId=None, vendor=None),
	FIXTag( 341, 'TradSesStartTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 342, 'TradSesOpenTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 343, 'TradSesPreCloseTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 344, 'TradSesCloseTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 345, 'TradSesEndTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 346, 'NumberOfOrders', repeatingHeaderId=None, vendor=None),
	FIXTag( 347, 'MessageEncoding', repeatingHeaderId=None, vendor=None),
	FIXTag( 348, 'EncodedIssuerLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 349, 'EncodedIssuer', repeatingHeaderId=None, vendor=None),
	FIXTag( 350, 'EncodedSecurityDescLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 351, 'EncodedSecurityDesc', repeatingHeaderId=None, vendor=None),
	FIXTag( 352, 'EncodedListExecInstLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 353, 'EncodedListExecInst', repeatingHeaderId=None, vendor=None),
	FIXTag( 354, 'EncodedTextLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 355, 'EncodedText', repeatingHeaderId=None, vendor=None),
	FIXTag( 356, 'EncodedSubjectLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 357, 'EncodedSubject', repeatingHeaderId=None, vendor=None),
	FIXTag( 358, 'EncodedHeadlineLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 359, 'EncodedHeadline', repeatingHeaderId=None, vendor=None),
	FIXTag( 360, 'EncodedAllocTextLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 361, 'EncodedAllocText', repeatingHeaderId=None, vendor=None),
	FIXTag( 362, 'EncodedUnderlyingIssuerLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 363, 'EncodedUnderlyingIssuer', repeatingHeaderId=None, vendor=None),
	FIXTag( 364, 'EncodedUnderlyingSecurityDescLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 365, 'EncodedUnderlyingSecurityDesc', repeatingHeaderId=None, vendor=None),
	FIXTag( 366, 'AllocPrice', repeatingHeaderId=None, vendor=None),
	FIXTag( 367, 'QuoteSetValidUntilTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 368, 'QuoteEntryRejectReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 369, 'LastMsgSeqNumProcessed', repeatingHeaderId=None, vendor=None),
	FIXTag( 370, 'OnBehalfOfSendingTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 371, 'RefTagID', repeatingHeaderId=None, vendor=None),
	FIXTag( 372, 'RefMsgType', repeatingHeaderId=None, vendor=None),
	FIXTag( 373, 'SessionRejectReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 374, 'BidRequestTransType', repeatingHeaderId=None, vendor=None),
	FIXTag( 375, 'ContraBroker', repeatingHeaderId=None, vendor=None),
	FIXTag( 376, 'ComplianceID', repeatingHeaderId=None, vendor=None),
	FIXTag( 377, 'SolicitedFlag', repeatingHeaderId=None, vendor=None),
	FIXTag( 378, 'ExecRestatementReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 379, 'BusinessRejectRefID', repeatingHeaderId=None, vendor=None),
	FIXTag( 380, 'BusinessRejectReason', repeatingHeaderId=None, vendor=None),
	FIXTag( 381, 'GrossTradeAmt', repeatingHeaderId=None, vendor=None),
	FIXTag( 382, 'NoContraBrokers', repeatingHeaderId=None, vendor=None),
	FIXTag( 383, 'MaxMessageSize', repeatingHeaderId=None, vendor=None),
	FIXTag( 384, 'NoMsgTypes', repeatingHeaderId=None, vendor=None),
	FIXTag( 385, 'MsgDirection', repeatingHeaderId=None, vendor=None),
	FIXTag( 386, 'NoTradingSessions', repeatingHeaderId=None, vendor=None),
	FIXTag( 387, 'TotalVolumeTraded', repeatingHeaderId=None, vendor=None),
	FIXTag( 388, 'DiscretionInst', repeatingHeaderId=None, vendor=None),
	FIXTag( 389, 'DiscretionOffset', repeatingHeaderId=None, vendor=None),
	FIXTag( 390, 'BidID', repeatingHeaderId=None, vendor=None),
	FIXTag( 391, 'ClientBidID', repeatingHeaderId=None, vendor=None),
	FIXTag( 392, 'ListName', repeatingHeaderId=None, vendor=None),
	FIXTag( 393, 'TotalNumSecurities', repeatingHeaderId=None, vendor=None),
	FIXTag( 394, 'BidType', repeatingHeaderId=None, vendor=None),
	FIXTag( 395, 'NumTickets', repeatingHeaderId=None, vendor=None),
	FIXTag( 396, 'SideValue1', repeatingHeaderId=None, vendor=None),
	FIXTag( 397, 'SideValue2', repeatingHeaderId=None, vendor=None),
	FIXTag( 398, 'NoBidDescriptors', repeatingHeaderId=None, vendor=None),
	FIXTag( 399, 'BidDescriptorType', repeatingHeaderId=None, vendor=None),
	FIXTag( 400, 'BidDescriptor', repeatingHeaderId=None, vendor=None),
	FIXTag( 401, 'SideValueInd', repeatingHeaderId=None, vendor=None),
	FIXTag( 402, 'LiquidityPctLow', repeatingHeaderId=None, vendor=None),
	FIXTag( 403, 'LiquidityPctHigh', repeatingHeaderId=None, vendor=None),
	FIXTag( 404, 'LiquidityValue', repeatingHeaderId=None, vendor=None),
	FIXTag( 405, 'EFPTrackingError', repeatingHeaderId=None, vendor=None),
	FIXTag( 406, 'FairValue', repeatingHeaderId=None, vendor=None),
	FIXTag( 407, 'OutsideIndexPct', repeatingHeaderId=None, vendor=None),
	FIXTag( 408, 'ValueOfFutures', repeatingHeaderId=None, vendor=None),
	FIXTag( 409, 'LiquidityIndType', repeatingHeaderId=None, vendor=None),
	FIXTag( 410, 'WtAverageLiquidity', repeatingHeaderId=None, vendor=None),
	FIXTag( 411, 'ExchangeForPhysical', repeatingHeaderId=None, vendor=None),
	FIXTag( 412, 'OutMainCntryUIndex', repeatingHeaderId=None, vendor=None),
	FIXTag( 413, 'CrossPercent', repeatingHeaderId=None, vendor=None),
	FIXTag( 414, 'ProgRptReqs', repeatingHeaderId=None, vendor=None),
	FIXTag( 415, 'ProgPeriodInterval', repeatingHeaderId=None, vendor=None),
	FIXTag( 416, 'IncTaxInd', repeatingHeaderId=None, vendor=None),
	FIXTag( 417, 'NumBidders', repeatingHeaderId=None, vendor=None),
	FIXTag( 418, 'TradeType', repeatingHeaderId=None, vendor=None),
	FIXTag( 419, 'BasisPxType', repeatingHeaderId=None, vendor=None),
	FIXTag( 420, 'NoBidComponents', repeatingHeaderId=None, vendor=None),
	FIXTag( 421, 'Country', repeatingHeaderId=None, vendor=None),
	FIXTag( 422, 'TotNoStrikes', repeatingHeaderId=None, vendor=None),
	FIXTag( 423, 'PriceType', repeatingHeaderId=None, vendor=None),
	FIXTag( 424, 'DayOrderQty', repeatingHeaderId=None, vendor=None),
	FIXTag( 425, 'DayCumQty', repeatingHeaderId=None, vendor=None),
	FIXTag( 426, 'DayAvgPx', repeatingHeaderId=None, vendor=None),
	FIXTag( 427, 'GTBookingInst', repeatingHeaderId=None, vendor=None),
	FIXTag( 428, 'NoStrikes', repeatingHeaderId=None, vendor=None),
	FIXTag( 429, 'ListStatusType', repeatingHeaderId=None, vendor=None),
	FIXTag( 430, 'NetGrossInd', repeatingHeaderId=None, vendor=None),
	FIXTag( 431, 'ListOrderStatus', repeatingHeaderId=None, vendor=None),
	FIXTag( 432, 'ExpireDate', repeatingHeaderId=None, vendor=None),
	FIXTag( 433, 'ListExecInstType', repeatingHeaderId=None, vendor=None),
	FIXTag( 434, 'CxlRejResponseTo', repeatingHeaderId=None, vendor=None),
	FIXTag( 435, 'UnderlyingCouponRate', repeatingHeaderId=None, vendor=None),
	FIXTag( 436, 'UnderlyingContractMultiplier', repeatingHeaderId=None, vendor=None),
	FIXTag( 437, 'ContraTradeQty', repeatingHeaderId=None, vendor=None),
	FIXTag( 438, 'ContraTradeTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 439, 'ClearingFirm', repeatingHeaderId=None, vendor=None),
	FIXTag( 440, 'ClearingAccount', repeatingHeaderId=None, vendor=None),
	FIXTag( 441, 'LiquidityNumSecurities', repeatingHeaderId=None, vendor=None),
	FIXTag( 442, 'MultiLegReportingType', repeatingHeaderId=None, vendor=None),
	FIXTag( 443, 'StrikeTime', repeatingHeaderId=None, vendor=None),
	FIXTag( 444, 'ListStatusText', repeatingHeaderId=None, vendor=None),
	FIXTag( 445, 'EncodedListStatusTextLen', repeatingHeaderId=None, vendor=None),
	FIXTag( 446, 'EncodedListStatusText', repeatingHeaderId=None, vendor=None),
	FIXTag( 454, 'NoSecurityAltID', repeatingHeaderId=None, vendor='CME', description='This tag is under development.'),
	FIXTag( 455, 'SecurityAltID', repeatingHeaderId=454, vendor='CME', description='This tag is under development.'),
	FIXTag( 456, 'SecurityAltIDSource', repeatingHeaderId=454, vendor='CME', description='This tag is under development.'),
	FIXTag( 461, 'CFICode', repeatingHeaderId=None, vendor='CME', description='Indicates the type of security using ISO 10962 standard, Classification of Financial Instruments (CFI code) values. See: http://www.cmegroup.com/confluence/display/EPICSANDBOX/Market+Data+-+CFICode+Table+of+Values'),
	FIXTag( 462, 'UnderlyingProduct', repeatingHeaderId=None, vendor='CME', description='Product complex (2=Commodity/Agriculture, 4=Currency, 5=Equity, 12=Other, 14=Interest Rate, 15=FX Cash, 16=Energy, 17=Metals)'),
	FIXTag( 555, 'NoLegs', repeatingHeaderId=None, vendor='CME', description='Number of legs.'),
	FIXTag( 556, 'LegCurrency', repeatingHeaderId=555, vendor='CME', description='Currency for this leg.'),
	FIXTag( 562, 'MinTradeVol', repeatingHeaderId=None, vendor='CME', description='The minimum trading volume for a security.'),
	FIXTag( 566, 'LegPrice', repeatingHeaderId=555, vendor='CME', description='Price for the futures leg of a covered.'),
	FIXTag( 600, 'LegSymbol', repeatingHeaderId=555, vendor='CME', description='Only sent for options strategies and futures spreads. '),
	FIXTag( 602, 'LegSecurityID', repeatingHeaderId=555, vendor='CME', description='Unique instrument ID for the leg.'),
	FIXTag( 603, 'LegSecurityIDSource', repeatingHeaderId=555, vendor='CME', description="Identifies source of tag 602-LegSecurityID value. This value is always '8' for CME."),
	FIXTag( 608, 'LegCFICode', repeatingHeaderId=555, vendor='CME', description='CFI code for this leg.'),
	FIXTag( 610, 'LegMaturityMonthYear', repeatingHeaderId=555, vendor='CME', description="Leg's MaturityMonthYear."),
	FIXTag( 612, 'LegStrikePrice', repeatingHeaderId=555, vendor='CME', description='Strike price of the leg.'),
	FIXTag( 616, 'LegSecurityExchange', repeatingHeaderId=555, vendor='CME', description='Security exchange of the leg.'),
	FIXTag( 620, 'LegSecurityDesc', repeatingHeaderId=555, vendor='CME', description='Leg security description (e.g., ESM0 C1130)'),
	FIXTag( 623, 'LegRatioQty', repeatingHeaderId=555, vendor='CME', description='The ratio of quantity for this individual leg relative to the entire multi-leg instrument.'),
	FIXTag( 624, 'LegSide', repeatingHeaderId=555, vendor='CME', description='1=Buy, 2=Sell.'),
	FIXTag( 711, 'NoUnderlyings', repeatingHeaderId=None, vendor='CME', description='Number of underlying instruments.'),
	FIXTag( 731, 'SettlPriceType', repeatingHeaderId=None, vendor='CME', description='Indicates whether settlement price is preliminary or final (1=Final, 2=Theoretical, 100=Actual preliminary for instruments not subject to rounding, 101=Actual preliminary for instruments subject to rounding).'),
	FIXTag( 762, 'SecuritySubType', repeatingHeaderId=None, vendor='CME', description='Indicates Strategy type.'),
	FIXTag( 764, 'LegSecuritySubType', repeatingHeaderId=555, vendor='CME', description='If leg repeating group is a spread, the strategy type for the spread.'),
	FIXTag( 779, 'LastUpdateTime', repeatingHeaderId=None, vendor='CME', description='Timestamp of when the instrument was deleted.'),
	FIXTag( 827, 'ExpirationCycle', repeatingHeaderId=None, vendor='CME', description="Indicates if the instrument expires at the trading session close, or at a specified last eligible trade date. If '0', the instrument is eligible for Day orders only. If '2', the instrument is eligible for GTC/GTD orders (outrights only). "),
	FIXTag( 864, 'NoEvents', repeatingHeaderId=None, vendor='CME', description='Number of repeating EventType entries.'),
	FIXTag( 865, 'EventType', repeatingHeaderId=864, vendor='CME', description='Code to represent the type of event (5=Activation, 7=Last eligible trade date)'),
	FIXTag( 866, 'EventDate', repeatingHeaderId=864, vendor='CME', description='Date of event.'),
	FIXTag( 870, 'NbInstAttrib', repeatingHeaderId=None, vendor='CME', description='Number of repeating group InstrAttribType entries.'),
	FIXTag( 871, 'InstAttribType', repeatingHeaderId=870, vendor='CME', description='Tag 871-InstAttribType and tag 872-InstAttribValue function together where tag 871 indicates the type of value that the following tag 872 will contain.'),
	FIXTag( 872, 'InstAttribValue', repeatingHeaderId=870, vendor='CME', description='Tag 871-InstAttribType and tag 872-InstAttribValue function together where tag 871 indicates the type of value that the following tag 872 will contain.'),
	FIXTag( 911, 'TotNumReports', repeatingHeaderId=None, vendor='CME', description='Total number of reports returned in response to a request.'),
	FIXTag( 942, 'LegStrikeCurrency', repeatingHeaderId=555, vendor='CME', description='Currency of the strike price of the leg.'),
	FIXTag( 947, 'StrikeCurrency', repeatingHeaderId=None, vendor='CME', description='Currency in which the strike price is denominated.'),
	FIXTag( 969, 'MinPriceIncrement', repeatingHeaderId=None, vendor='CME', description='Minimum constant tick for the instrument, sent only if instrument is non-VTT (Variable Tick table) eligible.'),
	FIXTag( 980, 'SecurityUpdateAction', repeatingHeaderId=None, vendor='CME', description='M=Modify, D=Delete.'),
	FIXTag( 996, 'UnitOfMeasure', repeatingHeaderId=None, vendor='CME', description="Unit of measure for the products' original contract size."),
	FIXTag(1017, 'LegOptionDelta', repeatingHeaderId=555, vendor='CME', description='Delta used to calculate the quantity of futures used to cover the option or option strategy.'),
	FIXTag(1022, 'MDFeedType', repeatingHeaderId=1141, vendor='CME', description='Describes a class of service for a given data feed.'),
	FIXTag(1093, 'LotType', repeatingHeaderId=1234, vendor='CME', description='The quantity type used for the leg of the spread. This tag is required to interpret the value in tag 1231-MinLotSize.'),
	FIXTag(1140, 'MaxTradeVol', repeatingHeaderId=None, vendor='CME', description='The maximum trading volume for a security.'),
	FIXTag(1141, 'NoMdFeedTypes', repeatingHeaderId=None, vendor='CME', description='Number of repeating FeedType repeating group entries.'),
	FIXTag(1142, 'MatchingAlgorithm', repeatingHeaderId=None, vendor='CME', description='Matching algorithm (F=FIFO, K=Configurable, C=Pro-Rata, A=Allocation, T=FIFO with LLM, O=Threshold Pro-Rata, S=FIFO with TOP and LLM, Q=Threshold Pro-Rata with LLM, Y=Eurodollar options)'),
	FIXTag(1143, 'MaxPriceVariation', repeatingHeaderId=None, vendor='CME', description='Differential value for price banding.'),
	FIXTag(1144, 'ImpliedMarketIndicator', repeatingHeaderId=None, vendor='CME', description='Informs the market that an instrument is eligible for implied trading (Implied In & Out; 0=Non-implied, 3=Implied). If this tag is not present, instrument is non-implied.'),
	FIXTag(1145, 'EventTime', repeatingHeaderId=864, vendor='CME', description='Time of event.'),
	FIXTag(1146, 'MinPriceIncrementAmount', repeatingHeaderId=None, vendor='CME', description='Under development.'),
	FIXTag(1147, 'UnitOfMeasureQty', repeatingHeaderId=None, vendor='CME', description='This field contains the contract size for each instrument (in combination with tag 996).'),
	FIXTag(1148, 'LowLimitPrice', repeatingHeaderId=None, vendor='CME', description='Lower price threshold for the instrument. Orders submitted with prices below the lower limit will be rejected.'),
	FIXTag(1149, 'HighLimitPrice', repeatingHeaderId=None, vendor='CME', description='Upper price threshold for the instrument. Orders submitted with prices above the upper limit will be rejected.'),
	FIXTag(1150, 'TradingReferencePrice', repeatingHeaderId=None, vendor='CME', description='The most recent settlement price.'),
	FIXTag(1151, 'SecurityGroup', repeatingHeaderId=None, vendor='CME', description='Product code.'),
	FIXTag(1180, 'AppIID', repeatingHeaderId=None, vendor='CME', description='The channel ID as defined in the XML Configuration file.'),
	FIXTag(1234, 'NoLotTypeRules', repeatingHeaderId=None, vendor='CME', description='Number of quantity types in the upcoming repeating group.'),
	FIXTag(1300, 'MarketSegmentID', repeatingHeaderId=None, vendor='CME', description='Identifies the market segment.'),
	FIXTag(1435, 'ContractMultiplierUnit', repeatingHeaderId=None, vendor='CME', description='Indicates the type of multiplier being applied to the product. Used in combination with tag 231. 1=Hour, 2=Day'),
	FIXTag(1439, 'FlowScheduleType', repeatingHeaderId=None, vendor='CME', description='The schedule according to which the electricity is delivered in a physical contract, or priced in a financial contract. '),
	FIXTag(5770, 'PriceRatio', repeatingHeaderId=None, vendor='CME', description='Used for price calculation in spread and leg pricing.'),
	FIXTag(5791, 'ClearedVolume', repeatingHeaderId=None, vendor='CME', description='Indicates the total cleared volume of instruments traded during the prior trading session.'),
	FIXTag(5792, 'OpenInterestQty', repeatingHeaderId=None, vendor='CME', description='Indicates the total open interest for the market at the close of the prior trading session.'),
	FIXTag(5795, 'LegSecurityGroup', repeatingHeaderId=555, vendor='CME', description='Product code for this leg.'),
	FIXTag(5796, 'TradingReferenceDate', repeatingHeaderId=None, vendor='CME', description='Indicates the date the last update to the settlement price.'),
	FIXTag(5818, 'DecayQty', repeatingHeaderId=None, vendor='CME', description='Indicates the quantity that a contract will decay daily by once the decay start date is reached.'),
	FIXTag(5819, 'DecayStartDate', repeatingHeaderId=None, vendor='CME', description='Indicates the date at which a decay contract will begin to decay.'),
	FIXTag(5849, 'OriginalContractSize', repeatingHeaderId=None, vendor='CME', description='Fixed contract value assigned to a product.'),
	FIXTag(9779, 'UserDefinedInstrument', repeatingHeaderId=None, vendor='CME', description='Y=User defined, N=Not.'),
	FIXTag(9787, 'DisplayFactor', repeatingHeaderId=None, vendor='CME', description='Contains the multiplier to convert the CME Globex display price to the conventional price.'),
	FIXTag(9850, 'MinCabPrice', repeatingHeaderId=None, vendor='CME', description='Defines cabinet price for outright options products.'),
	FIXTag(9853, 'PricingModel', repeatingHeaderId=None, vendor='CME', description='Identifies options pricing model (F=Fischer-Black, W=Whaley).'),
##### END GENERATED CODE
]

TAG_ID_TO_NAME = {}
TAG_NAME_TO_ID = {}
for tag in TAGS:
	assert(tag.id() not in TAG_ID_TO_NAME)
	TAG_ID_TO_NAME[tag.id()] = tag

	assert(tag.name() not in TAG_NAME_TO_ID)
	TAG_NAME_TO_ID[tag.name()] = tag

#Separate from the tags for ease of code generation
TAG_ENUM_VALUES = {
	35: {
		'0': 'Heartbeat',
		'1': 'Test Request',
		'2': 'Resend Request',
		'3': 'Reject',
		'4': 'Sequence Reset',
		'5': 'Logout',
		'6': 'Indication of Interest',
		'7': 'Advertisement',
		'8': 'Execution Report',
		'9': 'Order Cancel Reject',
		'A': 'Logon',
		'B': 'News',
		'C': 'Email',
		'D': 'Order - Single',
		'E': 'Order - List',
		'F': 'Order Cancel Request',
		'G': 'Order Cancel/Replace Request',
		'H': 'Order Status Request',
		'J': 'Allocation',
		'K': 'List Cancel Request',
		'L': 'List Execute',
		'M': 'List Status Request',
		'N': 'List Status',
		'P': 'Allocation ACK',
		'Q': 'Don\'t Know Trade',
		'R': 'Quote Request',
		'S': 'Quote',
		'T': 'Settlement Instructions',
		'V': 'Market Data Request',
		'W': 'Market Data-Snapshot/Full Refresh',
		'X': 'Market Data-Incremental Refresh',
		'Y': 'Market Data Request Reject',
		'Z': 'Quote Cancel',
		'a': 'Quote Status Request',
		'b': 'Quote Acknowledgement',
		'c': 'Security Definition Request',
		'd': 'Security Definition',
		'e': 'Security Status Request',
		'f': 'Security Status',
		'g': 'Trading Session Status Request',
		'h': 'Trading Session Status',
		'i': 'Mass Quote',
		'j': 'Business Message Reject',
		'k': 'Bid Request',
		'l': 'Bid Response',
		'm': 'List Strike Price'
	},
	54: {
		'1': 'Buy',
		'2': 'Sell',
		'3': 'Buy minus',
		'4': 'Sell plus',
		'5': 'Sell short',
		'6': 'Sell short exempt',
		'7': 'Undisclosed (valid for IOI and List Order messages only)',
		'8': 'Cross (orders where counterparty is an exchange, valid for all messages except IOIs)',
		'9': 'Cross short'
	},
	61: {
		'0': 'Normal',
		'1': 'Flash',
		'2': 'Background'
	},
	624: {
		'1': 'Buy',
		'2': 'Sell'
	},
	731: {
		'1': 'Final',
		'2': 'Theoretical',
		'100': 'Actual preliminary (instrument not subject to settlement price rounding)',
		'101': 'Actual preliminary (instrument subject to settlement price rounding)'
	},
	827: {
		'0': 'Expire on trading session close',
		'2': 'Expiration at given date'
	},
	865: {
		'5': 'Activation',
		'7': 'Last eligible trade date'
	},
	980: {
		'D': 'Delete',
		'M': 'Modify'
	},
	1093: {
		'2': 'Minimum order entry quantity',
		'3': 'Minimum quantity required for block trade',
		'4': 'Round lot (variable quantity products)'
	},
	1128: {
		'9': 'FIX50SP2',
	},
	1142: {
		'F': 'FIFO',
		'K': 'Configurable',
		'C': 'Pro-Rata',
		'A': 'Allocation',
		'T': 'FIFO with LLM',
		'O': 'Threshold Pro-Rata',
		'S': 'FIFO with TOP and LLM',
		'Q': 'Threshold Pro-Rata with LLM',
		'Y': 'Eurodollar options'
	},
	1144: {
		'0': 'Non-implied instrument',
		'3': 'Implied instrument'
	},
	1435: {
		'1': 'Multiplied by hour',
		'2': 'Multiplied by day'
	},
	9779: {
		'Y': 'User defined',
		'N': 'Not user defined'
	},
	9853: {
		'F': 'Fisher-Black',
		'W': 'Whaley'
	}
}
